import { PriceData } from '../../services/price.service';

export type PromptOutput = {
  role: string;
  content: string;
}[];

export type BatchInput = {
  custom_id: string;
  method: string;
  url: string;
  body: {
    model: string;
    messages: PromptOutput;
    max_tokens: number;
  };
};

/**
 * Interface representing a strategy adapter for mock trading.
 * Provides methods to execute strategies, prepare indicators, and generate prompts.
 */
export interface StrategyAdapter {
  /**
   * Executes the strategy using the provided price data points.
   *
   * @param dataPoints - An array of price data points used to execute the strategy.
   * @returns An array of batch inputs generated by the strategy execution.
   */
  execute(dataPoints: PriceData[]): BatchInput[];

  /**
   * Prepares indicators based on the provided price data.
   *
   * @param data - A single price data point used to prepare indicators.
   * @returns The prepared indicators in any format.
   */
  prepareIndicators(data: PriceData[]): any;

  /**
   * Generates a prompt output based on the provided indicator data.
   *
   * @param data - The indicator data used to generate the prompt.
   * @returns The generated prompt output.
   */
  generatePrompt(data: any): PromptOutput;
}
